development:
  adapter: postgresql
  database: deckard
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: deckard_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: deckard
  host: localhost
  pool: 5
  timeout: 5000
